# Generated by Django 5.1.4 on 2024-12-14 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_cart_created_at_alter_product_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 16, 52, 39, 849380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 16, 52, 39, 849380, tzinfo=datetime.timezone.utc)),
        ),
    ]
